Added Lab3
vgpnkw/LabsPPO pull request #4
Opened 2021-02-08 12:15 UTC by vgpnkw

https://drive.google.com/file/d/1UU-Yhqvjp8GLo4IS9OlyqL4J66rsfvCu/view?usp=sharing

2021-02-10 17:47 UTC, gmltA requested changes

2021-02-10 17:47 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    ArrayList<String> ships = new ArrayList<>();
All this goes to ViewModel. Along with business logic.

2021-02-10 17:47 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    int small = 3, medium = 2, huge = 1;
Looks like an `Enum`.

2021-02-10 17:47 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    protected void onCreate(Bundle savedInstanceState) {
Refactor. This method should not be couple of pages long.

2021-02-10 18:09 UTC, vgpnkw commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    protected void onCreate(Bundle savedInstanceState) {
Извините, вот здесь не совсем понял, что нужно переделать

2021-02-11 13:47 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    protected void onCreate(Bundle savedInstanceState) {
У вас метад на некалькі старонак. Апусцім тое, што ёсць нюансы спецыфічныя для платформы, але код, прынамсі, трэба раздзяліць на некалькі метадаў.

2021-02-12 09:53 UTC, vgpnkw commented
Исправил

2021-02-16 16:14 UTC, gmltA requested changes

2021-02-16 16:14 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +                gViewModel.setCell(field[i][j], i, j, buttonID);
You should not work with views in a ViewModel.

2021-02-17 19:49 UTC, vgpnkw commented
Исправил

2021-02-18 14:35 UTC, gmltA requested changes

2021-02-18 14:35 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/ActivityGame.java
> +    boolean isBattle = false;
Гэта ўсё таксама ў ViewModel.

2021-02-18 14:35 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/GameViewModel.java
> +    int [] temp = new int[2];
?

2021-02-18 14:35 UTC, gmltA commented on MyLab3/app/src/main/java/com/example/mylab3/GameViewModel.java
> +        temp = refactorString(buttonName);
Што гэта за дзіч? Вы каардынаты неяк больш зразумела даслаць можаце?

2021-03-18 13:06 UTC, closed without merging